@host=http://localhost:3010

###
# @name AdminLogin
POST {{host}}/_/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "p@ssw0rd"
}

###
@token = {{AdminLogin.response.body.token}}

###
POST {{host}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "testuser1",
    "password": "p@ssw0rd"
}

####
# @name User
GET {{host}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

###

@userId = {{User.response.body.data.[0].id}}

###
GET {{host}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{host}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "p0ssw@rd"
}

###
DELETE {{host}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/_/healthcheck

