@host=http://localhost:3010

###
# @name AdminLogin
POST {{host}}/_/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "p@ssw0rd"
}

###
@token = {{AdminLogin.response.body.token}}

POST {{host}}/role
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleName": "roletest1"
}

####
# @name Role
GET {{host}}/role
Content-Type: application/json
Authorization: Bearer {{token}}

###

@roleId = {{Role.response.body.data.[0].id}}

###
GET {{host}}/role/{{roleId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{host}}/role/{{roleId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleName": "SUPERADMIN"
}

###
DELETE {{host}}/role/{{roleId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/_/healthcheck

