run-start:
	K6_INFLUXDB_ORGANIZATION=belajar \
	K6_INFLUXDB_BUCKET=belajar-bucket \
	K6_INFLUXDB_ADDR=http://localhost:8086 \
	K6_INFLUXDB_TOKEN=wn-ncT13UuwXRcPLPTTmT6NuTnQp8x3UMaxzH-Bgw0OUxhyRr51HuSHKEaXwNK9UaaL-k4q4zELzoNdqWDLl3Q== \
	./k6 run src/script.js -o xk6-influxdb