scrape_configs:
  - job_name: "opentelemetry"
    scrape_interval: 5s
    static_configs:
      - targets: [fastify-app:9464]
  - job_name: "docker_stats_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [docker_stats_exporter:9487]
